apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ztouzri
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/killinq-joke/iot
    targetRevision: HEAD
    path: p3/kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true