apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mywebapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://172.18.0.2/root/test.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true