Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"

  # Define the first VM
  config.vm.define "ztouzriS" do |vm1|
    vm1.vm.box = "generic/alpine318"
    vm1.vm.hostname = "ztouzriS"
    vm1.vm.network "private_network", ip: "192.168.56.110"
    vm1.vm.provision "shell", path: "../scripts/init-controlplane.sh"
  end
end
