Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"

  # Define the first VM
  config.vm.define "ztouzriS" do |vm1|
    vm1.vm.box = "generic/alpine318"
    vm1.vm.hostname = "ztouzriS"
    vm1.vm.network "private_network", ip: "192.168.56.110"
    config.vm.synced_folder "./manifests/", "/home/vagrant/manifests/", type: "rsync"
    config.vm.synced_folder "./kustomize/", "/home/vagrant/kustomize/", type: "rsync"
    vm1.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "/tmp/id_ed25519.pub"
    vm1.vm.provision "shell", inline: <<-SHELL
      cat /tmp/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
      chmod 600 /home/vagrant/.ssh/authorized_keys
      rm /tmp/id_ed25519.pub
    SHELL
    vm1.vm.provision "shell", path: "./init-k3d.sh"
    # vm1.vm.provision "shell", inline: <<-SHELL
    #   sleep 10
    #   sudo kubectl apply -f "/home/vagrant/manifests/argo-ingress.yaml"
    # SHELL
    vm1.vm.provider "virtualbox" do |v|
      v.memory = 4092
      v.cpus = 2
    end
  end
end
